from .strategy import ARXIV_API, HEADERS, ML_CATEGORIES, ML_KEYWORDS, NS, SCIENCE_CATEGORIES, SCIENCE_KEYWORDS

# Backward-compatible aliases for older imports.
ML_CATS = ML_CATEGORIES
SCIENCE_CATS = SCIENCE_CATEGORIES
